
#Training
model: HGNN_time
dataset: primitive
fts_type: time
max_epoch: 1000
n_hid: 672
lr: 0.001
milestones: [100, 200, 300]
gamma: 0.7
drop_out: 0.2
print_freq: 10
weight_decay: 0
decay_step: 100
decay_rate: 0.7
early_stopping: 20